#!/usr/bin/env bash
# 取消以下环境变量
# BAILIAN_API_KEY, BAILIAN_BASE_URL, BAILIAN_MODEL, BAILIAN_VECTOR_STORE_ID
# DASHSCOPE_API_KEY
# HUNYUAN_API_KEY, HUNYUAN_BASE_URL
# MOONSHOT_API_KEY, MOONSHOT_BASE_URL
# OPENROUTER_API_KEY, OPENROUTER_BASE_URL
# QIANFAN_API_KEY, QIANFAN_BASE_URL, QIANFAN_MODEL

unset BAILIAN_API_KEY
unset BAILIAN_BASE_URL
unset BAILIAN_MODEL
unset BAILIAN_VECTOR_STORE_ID
unset DASHSCOPE_API_KEY
unset HUNYUAN_API_KEY
unset HUNYUAN_BASE_URL
unset MOONSHOT_API_KEY
unset MOONSHOT_BASE_URL
unset OPENROUTER_API_KEY
unset OPENROUTER_BASE_URL
unset QIANFAN_API_KEY
unset QIANFAN_BASE_URL
unset QIANFAN_MODEL

echo "已取消所有相关环境变量"
