name: CI-build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MoonBit
      uses: ./.github/actions/install-moonbit
      with:
        version: "0.1.20260703"

    - name: Run moon build
      run: moon update && moon build