name: CI-check

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MoonBit
      uses: ./.github/actions/install-moonbit

    - name: Run moon update
      run: moon update

    - name: Run moon check
      run: moon check

    - name: Run moon fmt check
      run: moon fmt --check

    - name: Run moon info check
      run: moon info
