name: CI-check

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MoonBit
      uses: ./.github/actions/install-moonbit

    - name: Run moon update and check
      run: moon update && moon check