name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build:
    needs: check
    uses: ./.github/workflows/build.yml